# CSV File

In [2]:
import csv
with open("data.csv","w",newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["venu","20","kkd"])
    writer.writerow(["gopal","25","hyd"])

# libraries
# Numpy

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
l=range(1000)
%timeit [i**2 for i in l]

178 μs ± 5.25 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
a=np.arange(1000)
%timeit a**2

3.06 μs ± 85 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# CREATING ARRAYS

In [8]:
a=np.array([1,2,3,4])
print(a.ndim)

1


In [9]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.ndim)

2


In [11]:
c=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [12]:
print(c.ndim)

3


In [13]:
print(a.shape)

(4,)


In [14]:
print(b.shape)

(2, 3)


In [15]:
print(c.shape)

(1, 4, 2)


# FUNCTIONS FOR CREATING ARRAY


In [16]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [18]:
#using linspace
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [19]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [22]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [23]:
print(np.diag(a))

[1 2 3 4]


# BASIC DATATYPES

In [24]:
a=np.arange(10)
print(a.dtype)

int64


In [25]:
a=np.arange(10,dtype="float")
print(a.dtype)

float64


In [26]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# OTHER DATATYPE

In [27]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [28]:
a=np.array([True,False])
print(a.dtype)

bool


In [33]:
a=np.array(['Lucky','Karthik'])
print(a.dtype)

<U7


# INDEXING AND SLICING

In [30]:
a=np.arange(10)
print(a[5])

5


In [31]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [32]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# SLICING

In [33]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(a[1:8:4])

[1 5]


In [35]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [36]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [37]:
a=np.arange(15)
a[5:]=7
a

array([0, 1, 2, 3, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

# COPIES & VIEWING

In [38]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [39]:
print(np.shares_memory(a,b))

True


In [40]:
b[0]=10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [41]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [42]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# RANDOM NUMBER GENERATOR

In [43]:
a=np.random.randint(0,25,15)
print(a)

[ 3  6 18 13  5  9 15 24  3 12  5 11  4 22 18]


In [44]:
mask=(a%2==0)

In [45]:
mask_a=a[mask]
print(mask_a)

[ 6 18 24 12  4 22 18]


In [34]:
# change in even places

In [47]:
a[mask]=-1
print(a)

[ 3 -1 -1 13  5  9 15 -1  3 -1  5 11 -1 -1 -1]


# ELEMENT WISE OPERATIONS

# 1. BASIC OPERATIONS

In [21]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [22]:
print(a**2)

[ 1  4  9 16]


# ALL ARITHMETIC OPERATES ELEMENT WISE

In [24]:
b=np.ones(4) +1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [25]:
print(a*b)

[2. 4. 6. 8.]


In [26]:
c=np.diag([1,2,3,4])
print(c)
print(c*c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [27]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# COMPARISION OPERATORS

In [28]:
a=np.array([1,2,3,4])
b=np.array([5,2,7,3])
print(a==b)

[False  True False False]


In [29]:
print(a>b)

[False False False  True]


In [30]:
print(a<b)

[ True False  True False]


In [33]:
# array wise comparision

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,c))
print(np.array_equal(a,b))

True
False


# LOGICAL OPERATORS

In [34]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")


In [35]:
print(np.logical_or(a,b))

[ True  True  True False]


In [36]:
print(np.logical_and(a,b))

[ True False False False]


In [37]:
print(np.logical_not(a,b))

[False  True False  True]


# TRIGNOMETRY/TRANSACTIONAL FUNCTIONS

In [38]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [39]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [35]:
np.log(a)

TypeError: ufunc 'log' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [41]:
a="Aditya Degree College"
print(a[::-1])

egelloC eergeD aytidA


In [46]:
a="Aditya Degree College"
b=""
for i in a:
    b=i+b
print(b)

egelloC eergeD aytidA


In [47]:
b=a.replace("e","r")
print(b)

Aditya Drgrrr Collrgr


In [48]:
a="Aditya Degree College"
b=""
for i in a:
    if i=="e":
        b+="r"
    else:
        b+=i
print(b)
    

Aditya Drgrrr Collrgr


In [50]:
b=a.split(",")
print(b)

['Aditya Degree College']
